// Auto-generated compressed course descriptions for chat context.
// Full descriptions remain in each department file for the website.
// This reduces the chat system prompt from ~47k to ~18k tokens.

export const compressedDescriptions: Record<string, string> = {
  'world-lit-h': 'Multicultural literature across four thematic units (Perspectives, Journey, Tradition/Change, Fate/Freewill) with analytical and persuasive writing.',
  'world-lit-r': 'Resource-level version of World Literature H.',
  'eng-10': 'American and British literature with descriptive, narrative, analytical, and expository essay writing.',
  'eng-10-r': 'Resource-level version of English 10.',
  'eng-10-h': 'American writers from pre-Colonial to present with introduction to British literature; emphasis on discussion and analysis.',
  'eng-11': 'Thematic exploration of Voice/Tradition, Race/Class, Leadership, Gender through Romanticism to contemporary movements.',
  'eng-11-h': 'Twentieth-century American and English literature emphasizing close reading and genre-based essay writing.',
  'eng-11-r': 'Resource-level version of English 11.',
  'ap-eng-lang': 'College-level expository, analytical, and argumentative nonfiction prose with rhetorical analysis and research synthesis.',
  'eng-12-h': 'Five units (Genocide, Stranger, Self/Society, Memoir, Film) with film analysis and alternative assessment.',
  'eng-12': 'Four units (Self/Society, Migrations, Genocide, Page to Stage) preparing students for college and career.',
  'eng-12-r': 'Resource-level version of English 12.',
  'ap-eng-lit': 'Literature analysis through text and open-ended questions with research synthesis and peer review.',
  'african-am-lit-1': 'African-American literature from Ancient Africa through Harlem Renaissance with oral presentation and research.',
  'african-am-lit-2': 'African-American writers from Harlem Renaissance to present in poetry, novels, drama, and nonfiction.',
  'film-and-lit': 'Adaptation analysis: examines how fiction/drama translate to film; explores film as historical artifact.',
  'hip-hop-lit': 'Hip-Hop poetry\'s formation, cultural/geographical development, and role in social change versus perpetuating stereotypes.',
  'jewish-lit': 'Jewish literary tradition from Bible to twentieth century; special focus on Holocaust literature including Maus.',
  'diaspora-lit': 'Latino/Muslim/Asian/Black writers examining identity, transnationalism, immigration, race, gender, inequality through contemporary texts.',
  'philosophy-comp': 'Central philosophical questions (god, mind-body, AI, ethics, meaning) through discussion, arguments, and thought experiments.',
  'satire-dystopian': 'Social criticism across classical to contemporary forms; second semester examines dystopian subgenre of satire.',
  'short-stories': 'American, British, world short fiction emphasizing theme, character, plot, style with creative story writing.',
  'sports-lit': 'Sport\'s influence on society examining race, gender, nationalism, education through fiction and nonfiction.',
  'womens-lit': 'Women authors across genres examining identity, societal expectations, gender intersecting with race, class, sexuality.',
  'creative-writing': 'Poetry, drama, short stories, creative nonfiction with workshop critique and multimedia digital projects.',
  'essay-skill-dev': 'Vocabulary, reading comprehension, essay writing, test strategy, and college entrance essay preparation.',
  'read-write-think-1': 'Workshop course developing pre-writing, mapping, free writing, revision, and editing through discussion and collaboration.',
  'read-write-think-2': 'Continuation of Read, Write, Think I with daily reading and writing workshop experiences.',
  'multisensory-reading-9': 'Resource-level multisensory reading remediation using Wilson, Orton-Gillingham, Lindamood-Bell for Grade 9.',
  'multisensory-reading-10': 'Resource-level multisensory reading remediation using Wilson, Orton-Gillingham, Lindamood-Bell for Grade 10.',
  'multisensory-reading-11': 'Resource-level multisensory reading remediation using Wilson, Orton-Gillingham, Lindamood-Bell for Grade 11.',
  'multisensory-reading-12': 'Resource-level multisensory reading remediation using Wilson, Orton-Gillingham, Lindamood-Bell for Grade 12.',
  'esl-9': 'English language acquisition for non-native speakers; listening, speaking, reading, writing, and study skills.',
  'esl-10': 'English language acquisition for non-native speakers; listening, speaking, reading, writing, and study skills.',
  'esl-11': 'English language acquisition for non-native speakers; listening, speaking, reading, writing, and study skills.',
  'esl-12': 'English language acquisition for non-native speakers; listening, speaking, reading, writing, and study skills.',
  'esl-newcomers-a': 'Foundational ESL with American cultural emphasis; simple to challenging fiction/nonfiction and grammatical writing development.',
  'esl-newcomers-b': 'Foundational ESL with American cultural emphasis; simple to challenging fiction/nonfiction and grammatical writing development.',
  'esl-beginners-a': 'Beginner ESL developing four language domains with organizational and writing strategies in safe environment.',
  'esl-beginners-b': 'Beginner ESL developing four language domains with organizational and writing strategies in safe environment.',
  'esl-intermediate-a': 'Intermediate ESL reading fluency and essay writing through process writing, discussion, and formal presentations.',
  'esl-intermediate-b': 'Intermediate ESL reading fluency and essay writing through process writing, discussion, and formal presentations.',
  'esl-advanced-a': 'Advanced ESL cognitive academic language with sophisticated reading comprehension and multi-purpose writing.',
  'esl-advanced-b': 'Advanced ESL cognitive academic language with sophisticated reading comprehension and multi-purpose writing.',
  'esl-transitional': 'Advanced students transitioning to mainstream coursework; academic essay writing and literary genres for college.',
  'esl-support': 'Supplemental ESL tutorial paired with core ESL course for intensive English instruction and academic integration.',
  'alg-1-h': 'Fast-paced honors algebra with operations, set theory, linear equations, graphing functions, statistics, and probability.',
  'alg-1': 'Introduction to algebraic symbols, linear equations, inequalities, graphing functions, statistics, and probability.',
  'alg-1-r': 'Resource-level version of Algebra I.',
  'geom-h': 'Rigorous geometry with deductive reasoning, logic proofs, area, volume, and coordinate geometry for advanced students.',
  'geom': 'Geometry fundamentals: points, lines, polygons, circles, deductive proofs, area, volume, coordinate geometry.',
  'geom-r': 'Resource-level version of Geometry.',
  'alg-2-trig-h': 'Fast-paced algebra with in-depth trigonometry including identities and applications; prepares for AP Precalculus.',
  'alg-2-h': 'Functions, polynomials, rational expressions, quadratics, exponential/logarithmic functions, complex numbers.',
  'alg-2': 'Solving and graphing polynomial, rational, radical, exponential equations with systems and complex numbers.',
  'alg-2-r': 'Resource-level version of Algebra II.',
  'ap-precalc-calc': 'Trigonometric functions, identities, polar coordinates, plus differential calculus limits, derivatives, and applications.',
  'precalc-h': 'Trigonometric and circular functions, logarithms, rational function graphs, limits with advanced algebraic concepts.',
  'precalc': 'Circular and trigonometric functions with real-life applications at traditional pace.',
  'ap-precalc': 'College-level functions and modeling across multiple representations for STEM and data science careers.',
  'applied-math': 'Resource-level course blending Algebra I, Geometry, Algebra II through contemporary mathematical modeling.',
  'ap-calc-bc': 'Comprehensive calculus: limits, derivatives, integrals, Taylor polynomials, series convergence, polar coordinates, parametric functions.',
  'ap-calc-ab': 'Differential and integral calculus: limits, derivatives, integrals, related rates, optimization, area/volume.',
  'calc-h': 'Calculus theory and applications: limits, derivatives, integrals, maxima/minima, related rates, exponential/trig functions.',
  'calc-3-hh': 'Multivariable calculus: vector functions, multiple integration, directional derivatives, vector analysis in three dimensions.',
  'ap-stats': 'Technology-based introductory statistics: data exploration, study design, probability, simulation, statistical inference.',
  'prob-stats-h': 'Data exploration, probability, simulation, and statistical inference as alternative to calculus.',
  'prob-stats': 'Data exploration, probability, simulation, statistical inference for fourth-year math alternative to Pre-Calculus.',
  'ap-bio': 'College-level biology covering cellular function, genetics, evolution, biotechnology, and ecology with extensive lab work.',
  'bio-h': 'Foundational 9th-grade biology emphasizing cell structure, genetics, evolution, and ecology through experimental design and communication.',
  'bio-r': 'Resource-level version of Biology H.',
  'anatomy-h': 'Human anatomy and physiology with emphasis on structure-function relationships, homeostasis, and pathological conditions.',
  'marine-bio': 'Ocean systems, marine organisms, and marine life diversity through study of preserved specimens and field resources.',
  'bioethics': 'Social and ethical implications of biotechnology, medical research, and policy decisions in biology and healthcare.',
  'geosci-h': 'Earth\'s physical systems integrated through chemistry and physics: geochemistry, tectonics, geomorphology, climate, astrophysics.',
  'geosci': 'Earth\'s physical systems integrated through chemistry and physics: geochemistry, tectonics, geomorphology, climate, astrophysics.',
  'geosci-r': 'Resource-level version of Geoscience.',
  'ap-enviro': 'College-level environmental science using quantitative analysis to examine human-environmental interactions and solutions.',
  'enviro-h': 'Multidisciplinary environmental science combining ecology, geology, oceanography, meteorology, and chemistry.',
  'enviro': 'Multidisciplinary environmental science combining ecology, geology, oceanography, meteorology, and chemistry.',
  'enviro-r': 'Resource-level version of Environmental Science.',
  'astronomy': 'Solar systems, stars, planets, black holes, quantum phenomena, and cultural/historical contexts of astronomy.',
  'ap-chem': 'College-level chemistry covering atomic structure, bonding, reactions, kinetics, thermodynamics, and equilibrium.',
  'chem-h': 'Comprehensive chemistry covering atomic structure, chemical reactions, the periodic table, and science-math problem-solving.',
  'chem': 'Atomic structure, nomenclature, chemical reactions, mole concept, gas laws, acid-base behavior, and science-math skills.',
  'chem-r': 'Resource-level version of Chemistry.',
  'ap-physics-1': 'First-semester algebra-based college physics: mechanics, momentum, energy, gravitation, oscillations, and fluids.',
  'ap-physics-2': 'Second-semester algebra-based college physics: thermodynamics, electricity, magnetism, optics, and nuclear physics.',
  'ap-physics-c1': 'First-semester calculus-based college physics for engineering: motion, forces, energy, angular motion, and gravitation.',
  'ap-physics-c2': 'Second-semester calculus-based college physics: electric forces, magnetism, electromagnetism, and circuits.',
  'physics-h': 'Practical physics for juniors/seniors: vectors, kinematics, Newton\'s laws, momentum, energy with heavy trigonometry.',
  'physics': 'Motion, force, momentum, energy; algebra-based problem-solving with scientific notation and graphical analysis.',
  'forensic-sci': 'Criminal investigation fundamentals and courtroom application through lab analysis, case studies, and law enforcement activities.',
  'stem-pbl': 'Project-based STEM learning across four thematic units emphasizing application, foundations, development, and communication.',
  'weston-scholars': 'Summer research program with Montclair State University faculty plus mathematics component and 20 hours community service.',
  'global-studies-h': 'Studies six world regions (Middle East, Africa, Latin America, South/Southeast Asia) through geographic, historical, political, economic, social, and cultural perspectives.',
  'global-studies-r': 'Resource-level version of Global Studies H.',
  'us-hist-1': 'American history from Independence to 1900: colonization, revolution, Westward expansion, Civil War, Reconstruction, industrialization, and imperialism.',
  'us-hist-1-h': 'Thematic analysis of America 1491–1900 through inquiry: establishing new nation, expansion/reform, Civil War/Reconstruction, industrialization/urbanization with primary sources and debates.',
  'us-hist-1-hh': 'AP-level America 1491–1877: pre-Columbian Americas, colonial societies, Revolution, republic expansion, slavery tensions, Civil War aftermath using college textbooks and DBQs.',
  'us-hist-1-r': 'Resource-level version of U.S. History I.',
  'us-hist-2': 'American history 1900–present: Progressive Era, World Wars, Depression, Cold War, Civil Rights, counterculture, Vietnam, Watergate, Reagan, and digital age.',
  'us-hist-2-h': '20th–21st century America: WWI through internet age with emphasis on independent reading, research, library skills, and expository essay writing.',
  'ap-us-hist': 'AP continuation (1898–present): industrialization, overseas expansion, WWII, Cold War, Civil Rights, Vietnam with SAQs, FRQs, DBQs preparation for AP exam.',
  'us-hist-2-r': 'Resource-level version of U.S. History II.',
  'holocaust-genocide': 'Holocaust and genocide in comparative context: Identity, Genocide History, Justice, Legacy, examining moral dilemmas and patterns to prevent recurrence.',
  '20th-century-culture': 'Origins of American 20th-century culture through art, music, film, literature, technology analyzing government responses with writing, research, multimedia presentation skills.',
  'am-foreign-policy-h': '20th-century American foreign policy: evaluating effectiveness, predicting outcomes, conflict resolution with adversaries and allies in real-life diplomatic scenarios.',
  'african-am-hist': 'African American experience from African origins to present: origins, developments, contributions as major force in American history with critical thinking focus.',
  'cultural-pluralism': 'Sociological analysis of inequality (gender, race, class) across work, family, education, health, justice, sexuality using literature, film, documentaries.',
  'women-of-world': 'Global women\'s experience: interlocking systems of racism, sexism, colonialism, globalization and feminist resistance movements using literature, film, music, podcasts.',
  'microecon-h': 'Market mechanisms: supply/demand, buyer-seller interaction, market structures, consumer behavior, costs, government addressing market failures with real-world case studies.',
  'macroecon-h': 'National economies: national income, price levels, growth, international trade, Fed tools (taxes, spending, money supply) influencing growth, jobs, stability.',
  'monetary-policy-h': 'No course description provided. Contact Social Studies department for details.',
  'ap-african-am-studies': 'African Diaspora 900 BCE–present: origins, enslavement/resistance, freedom practice (Reconstruction, Jim Crow), 20th–21st-century movements with primary source analysis.',
  'ap-euro-hist': 'European history 1450–21st century: political, cultural, social, intellectual heritage preparing students for AP exam and college credit.',
  'ap-world-hist': 'Global evolution 1200 CE–present: periodization, change/continuity, comparison across major societies emphasizing interpretive frameworks and historical evidence.',
  'ap-human-geo': 'Spatial relationships: population, migration, culture, language, religion, ethnicity, politics, development, industry, urban geography, agriculture with local/regional/global case studies.',
  'ap-psych': 'Behavior and mental processes: biological bases, sensation, learning, cognition, development, testing, abnormal behavior, social psychology with experiments and authentic research.',
  'mandarin-1-h': 'Mandarin basics with listening/speaking emphasis and cultural introduction.',
  'mandarin-2-h': 'Intermediate Mandarin balancing all four skills with deeper Chinese history.',
  'mandarin-3-h': 'Advanced communicative Mandarin handling complex situations with focus on reading/writing.',
  'mandarin-4-h': 'Mastery of character reading/writing alongside complex language skills and cultural ideology.',
  'ap-chinese': 'Fourth-semester college-level Mandarin proficiency across three communication modes.',
  'spanish-1-r': 'Resource-level version of Spanish I.',
  'spanish-1': 'Spanish fundamentals emphasizing listening and speaking from day one.',
  'spanish-1-h': 'Honors Spanish I with critical thinking, research, and double pacing.',
  'spanish-2': 'Indicative tenses, reading comprehension, and cultural discussions in Spanish.',
  'spanish-2-h': 'Accelerated Spanish proficiency through inquiry-based projects and all communication modes.',
  'spanish-3': 'Hispanic historical figures, Spain/Latin American culture and literature.',
  'spanish-3-h': 'Spanish communicative proficiency grounded in cultural readings and historical Hispanic perspectives.',
  'spanish-4': 'Spanish/Latin American literature, television, and cultural analysis.',
  'spanish-4-h': 'Advanced Spanish through authentic news, videos, art, music for AP preparation.',
  'ap-spanish-5': 'Sixth themes (families, technology, aesthetics, challenges, life, identity) in College Board format.',
  'ap-spanish-6': 'Advanced Spanish literature study of College Board-required authors.',
  'spanish-6-hh-cinema': 'Spanish films analyzed as art via cinematography, culture, symbolism, and literary coordination.',
  'french-1-h': 'Conversational French with present tense basics and cultural lessons integrated.',
  'french-2-h': 'Past tense introduction and object pronouns with fluency-focused oral work.',
  'french-3-h': 'Intermediate-low proficiency through travel, daily routines, and city life topics.',
  'french-4-h': 'Three communication modes via literature excerpts, newspapers, authentic media.',
  'ap-french-5': 'Six themes (challenges, technology, life, identity, families, aesthetics) at advanced level.',
  'french-6-hh': 'Third-year college-equivalent French literature: drama, prose, poetry, cinema.',
  'german-1-h': 'German pronunciation, grammar, TPR methods, geography of German-speaking countries.',
  'german-2-h': 'Conversational past tense, case concepts, 19th-20th century poetry memorization.',
  'german-3-h': 'Sophisticated grammar, case relationships, word order, and fiction reading.',
  'german-4-h': 'Fine-tuned communication via German poetry memorization and crime novel reading.',
  'italian-1-h': 'Italian fundamentals emphasizing listening and speaking with cultural introduction.',
  'italian-2-h': 'Italian grammar through dialogues and readings about culture and civilization.',
  'italian-3-h': 'Major Italian writers and literature study building on two years foundation.',
  'italian-4-h': 'Italian literary works with emphasis on speaking, reading comprehension, critical thinking.',
  'latin-1-h': 'Latin grammar fundamentals, simple story translation, Roman daily life and mythology.',
  'latin-2-h': 'Simplified classical Latin literature excerpts with grammar, government, military history.',
  'latin-3-h': 'Complex grammar, original passages, myths, culture, Roman art of war.',
  'latin-4-h': 'All declensions/conjugations, subjunctive mastery, Caesar/Cicero/Vergil/Ovid poetry.',
  'art-foundations': 'Two- and three-dimensional studio fundamentals covering Elements of Art and Principles of Design.',
  'drawing': 'Observational drawing across still life, perspective, portraiture, figure, and landscape with multiple media.',
  'painting-1': 'Introduction to color theory, paint techniques, and composition with emphasis on developing artistic voice.',
  'painting-2': 'Advanced painting with independent projects, conceptual components, and art historical context.',
  'fibers-textile': 'Weaving, surface design, and non-woven processes with cultural and historical analysis.',
  'ceramics-1': 'Hand-building clay techniques emphasizing functional pottery, glazing, and cross-cultural traditions.',
  'ceramics-2-h': 'Advanced hand-building and potter\'s wheel with refined surface treatments and glazing methods.',
  'sculpture': 'Space, volume, form, and material exploration from prehistoric to contemporary world traditions.',
  'web-design': 'HTML, CSS, and web page creation using modern internet publishing tools.',
  'digital-design-imaging': 'Illustrative and photo manipulation software with CAD for 2D-to-3D digital printing.',
  'graphic-design': 'Fundamental principles and practices of effective visual communication through design.',
  'cad': '3D modeling with TinkerCad and hands-on 3D printing with industrial equipment.',
  'photography': 'Photography fundamentals, technical skills, artistic principles, and portfolio development.',
  'creative-coding': 'Graphic design principles and visual communication through creative code.',
  'art-1-h': 'Intermediate drawing, painting, and critique emphasizing composition, color theory, and life drawing.',
  'art-2-h': 'Advanced media exploration with charcoal, ink, pastel, watercolor, acrylic, and mixed media.',
  'ap-art-design': 'College-level portfolio preparation in Drawing, 2-D Design, or 3-D Design for AP submission.',
  'senior-portfolio-h': 'Portfolio development for art school/college entry with artistic concept refinement.',
  'ap-art-history': 'Global art history from prehistory to present with visual, contextual, and comparative analysis.',
  'acting-1': 'Improvisation, vocal/physical skills, emotional recall, scene and monologue work.',
  'acting-2': 'Performance styles from Theatre History with ensemble building and original work creation.',
  'acting-3': 'Theatre for Social Change through ensemble work, character development, and devised pieces.',
  'tech-theater': 'Backstage fundamentals including stage management, sets, costumes, and lighting design.',
  'film-making': 'Cinematography, lighting, sound, screenplay format, and filmmaking industry jobs.',
  'intro-dance': 'Foundational modern, contemporary, ballet, jazz, and cultural dance with improvisation.',
  'intermediate-dance': 'Intermediate technique across genres with choreography, improvisation, and dance critique.',
  'advanced-dance': 'Kinesthetic mastery with advanced turning, rhythmic phrasing, and collaborative choreography.',
  'music-appreciation': 'Global music history, American cultural music, piano fundamentals, and recording arts.',
  'music-theory-1-h': 'Notation, rhythm, intervals, scales, chords, sight-singing, ear training, and basic piano.',
  'ap-music-theory': 'Classical notation, scales, chords, transposition, composition, and ear training with notation software.',
  'music-theory-2-hh': 'Advanced composition techniques and styles with aural skills and computer-assisted notation.',
  'intro-band': 'Beginner band fundamentals, instrument technique, ensemble playing, and graduation performance.',
  'band-h': 'Concert and football band with jazz, pep band, and orchestra opportunities.',
  'orchestra-h': 'String ensemble performances across multiple concerts with seasonal performance opportunities.',
  'mixed-chorus': 'Vocal ensemble with rock-influenced instrumental accompaniment for varied skill levels.',
  'chorus': 'Vocal ensemble with instrumental accompaniment, modern rock approach, for varied skill levels.',
  'choir-h': 'Advanced choral ensemble emphasizing music theory, sight-reading, ear-training, and vocal production.',
  'madrigal-choir-h': 'Select singers with 3+ years training performing high-standard repertoire and theory skills.',
  'yearbook-1': 'Page design, typography, publishing, editing, and photography producing school yearbook.',
  'yearbook-2': 'Resource-level version of Yearbook I.',
  'yearbook-3': 'Resource-level version of Yearbook I.',
  'intro-marketing': 'Marketing mix, strategy development, consumer product design, and foreign market regulations.',
  'intro-advertising': 'Advertising\'s political, economic, social, cultural role; consumer/object relationships and media analysis.',
  'journalism-1': 'Newsworthiness, fair reporting, ethical journalism, First Amendment; publish to student newspaper.',
  'journalism-2': 'Critical news consumption and research skills; multiformat journalism (print, broadcast, digital, podcast).',
  'intro-business': 'Business functions, ownership forms, entrepreneurship fundamentals, budgeting, and trend forecasting.',
  'entrepreneurial-study': 'Business planning, market research, marketing strategies, financial management, and venture development.',
  'finance': 'Personal financial planning, investing, budgeting, insurance, housing, job selection; satisfies literacy requirement.',
  'cs-1-h': 'Hardware/software troubleshooting, network security; disassemble computers, graphics, programming, 3D modeling.',
  'ap-cs-a': 'Java programming, object-oriented design, data structures, algorithms; college-equivalent with lab component.',
  'ap-cs-principles': 'Computational thinking across disciplines; programming, algorithms, cybersecurity, big data, internet impacts.',
  'culinary-1': 'Food safety, nutrition, knife skills, recipe development, food science careers.',
  'culinary-2': 'Advanced cooking techniques, in-depth nutrition, food entrepreneurship, social media marketing.',
  'carpentry-1a': 'Shop safety, tools, hand skills; plumb, level, square; math, geometry, physics applied.',
  'carpentry-1b': 'Intermediate projects and complex construction techniques building on Carpentry 1A fundamentals.',
  'carpentry-2a': 'Student-directed projects: research, design, house construction layout, materials, and pricing.',
  'carpentry-2b': 'Advanced capstone with complex projects applying full carpentry sequence skills.',
  'robotics-1': 'Machine shop operations and basic electrical circuits with hands-on labs.',
  'robotics-2-h': 'Custom contract goals, engineering portfolio tracking, tech competition participation.',
  'robotics-3-h': 'Advanced projects, portfolio development, competition participation; continuation of Robotics II.',
  'robotics-4-h': 'Capstone course: advanced projects, portfolio development, technology competition participation.',
  'automotive-1': 'Safety inspections, preventative maintenance, fluid intervals, routine car care.',
  'automotive-2': 'Entry-level career prep; disassemble, repair in realistic shop setting.',
  'power-technology': 'Two and four-cycle engine theory, rebuilding, equipment servicing.',
  'intro-architecture': 'Sketching, perspective drawing, design process, architectural history, drafting, model building.',
  'arch-design-1': 'Residential and commercial design; commercial facades, tiny homes, pavilions; writing, drafting, math.',
  'arch-design-1-h': 'Residential and commercial design; commercial facades, tiny homes, pavilions; writing, drafting, math.',
  'arch-design-2-h': 'Design challenges with structural/material emphasis; sustainable solutions to conflicting requirements.',
  'arch-design-3-h': 'Architecture, structural engineering, civil engineering, social/historic aspects; furniture, theater, landscape design.',
  'health-9': 'Critical thinking and decision-making skills for personal, family, and community health wellness.',
  'drivers-ed-10': 'Comprehensive driver training covering New Jersey requirements and vehicle operation safety.',
  'health-11': 'Prevention and management of six primary young adult health issues: injury, substance abuse, STIs, contraception, stress, weight.',
  'health-12': 'Marriage, parenting, college preparation, budgeting and life skills for post-secondary transitions.',
  'adaptive-pe': 'Individualized motor activities and fitness prescription for students with learning and physical disabilities.',
  'pe-aerobics': 'Aerobic exercise physiology, cardiovascular endurance and individual fitness.',
  'pe-archery': 'Lifetime sport with target shooting, precision techniques and aerodynamics.',
  'pe-badminton': 'Lifetime sport with basic skill development, individual fitness and sportsmanship.',
  'pe-balls-and-bands': 'Full-body toning using cost-effective fitness equipment (stability balls, resistance bands).',
  'pe-basic-tumbling': 'Beginner to intermediate tumbling skills and routine development.',
  'pe-basketball': 'Intermediate basketball skills, offensive/defensive strategies and tournament play.',
  'pe-cardio-training': 'Heart rate monitoring, target zones using monitors and pedometers at local YMCA.',
  'pe-circuit-training': 'Strength and conditioning without specialized equipment for cardiovascular endurance.',
  'pe-cooperative-games': 'Teamwork-focused games toward common goals emphasizing fair play.',
  'pe-core-training': 'Core strengthening using medicine balls and BOSU balls to reduce injuries.',
  'pe-creative-movement': 'Movement education with music, rhythm and routine choreography.',
  'pe-flag-football': 'Non-contact football with position play and offensive/defensive strategies.',
  'pe-floor-hockey': 'Ice and field hockey skills combined with tournament play.',
  'pe-golf': 'Lifetime sport with game strategies, etiquette and individual fitness.',
  'pe-gymnastics': 'Intermediate to advanced gymnastics skills with routine creation.',
  'pe-lacrosse': 'Basic lacrosse skills, tournament participation and sport-specific rules.',
  'pe-meditation': 'Mind-body connection, breathing techniques and stress reduction.',
  'pe-pilates': 'Core muscle strength development emphasizing balance and stability.',
  'pe-soccer': 'Intermediate soccer skills, offensive/defensive strategies and tournament play.',
  'pe-softball': 'Intermediate to advanced softball with strategies and tournament participation.',
  'pe-speedball': 'Integrated sport combining soccer, basketball and football skills.',
  'pe-sport-education': 'Volleyball, tennis, badminton emphasizing sportsmanship and character development.',
  'pe-sport-of-sorts': 'Mini units in mass games, individual fitness and unique team sports.',
  'pe-tai-chi': 'Mind-body connection through flowing movement focusing on balance and strength.',
  'pe-team-handball': 'New sport with basic skill development and modified game participation.',
  'pe-tennis': 'Intermediate to advanced tennis techniques, tournament play and etiquette.',
  'pe-ultimate-frisbee': 'Fast-paced team activity emphasizing teamwork and transition defense.',
  'pe-volleyball': 'Intermediate volleyball skills, tournament play and team effectiveness.',
  'pe-weight-training': 'Resistance training with proper form, muscle tone and individual progression.',
  'pe-yoga': 'Mind-body connection combining poses, relaxation and flexibility development.',
  'sped-study-skills': 'Time management, note-taking, outlining, and test-taking strategies with individualized support for general education classes.',
  'sped-skills-life-work': 'Career exploration, job application/interview prep, resume writing, and workplace behavior skills with self-assessment.',
  'sped-work-study': 'Community work sampling combined with job application, interview prep, and workplace skills development.',
  'sped-self-contained': 'Structured environment with greater individualization (3-5 periods daily); specialized core academics per IEP requirements.',
  'sped-cbi': 'Ages 18-21: community connections, employment preparation, and life skills for students with significant disabilities post-graduation.',
};
